### ISSUE TITLE
error when adding your plugin

### ISSUE THREAD

**Issue by kirrg001** [getlackey/mongoose-version#1]
mongoose version: 4.0.5

```
TypeError: Undefined type `undefined` at `paths._id`
  Did you try nesting Schemas? You can only nest using refs or arrays.
    at Schema.<anonymous> (/..../node_modules/lackey-mongoose-version/lib/save-collection.js:28:39)
```

After you clone the schema and create a new one, i get an error.
suggestions?

**Comment by kirrg001** [comment]
question is:

```
        // Add reference to model to original schema
        var VersionedModel = Model.db.model(options.collection, versionedSchema);

        schema.statics.VersionedModel = VersionedModel;
        Model.VersionedModel = VersionedModel;
```

why do you not simply reference with _id?
so the copied version model schema has a reference to the original instance?

**Comment by relvao** [comment]
We are still using an older version of mongoose (3.8.23) where it works. I'll update and check it.

**Comment by relvao** [comment]
@kirrg001 I can't see the error using mongoose@4.0.5. Can you provide some example code?

Thanks

**Comment by glebcha** [comment]
Same error.

**Comment by relvao** [comment]
It should be solved now. The plugin was installing version mongoose 3.8 and that created an incompatibility. Removing the dependency from the plugin solves the issue. 

Given that mongoose don't follow semver, setting that dependency in the package.json has little value as no one would use the plugin without mongoose and I can't see how to ensure a compatible version without limiting the version to the current tested one, without any bugfixes. 

I'm leaving it as is for now. Does anyone have a better idea?
