### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by glutz** [getlackey/mongoose-version#2]
Hi
just want to ask if this mongoose-version is working with mongoose 3. Used the original mongoose-version and had trouble with this after changing to mongoose 3.
thanks for a short information.
KR
Günter

**Comment by relvao** [comment]
Hi.

I'm using Mongoose 3.8.23. As far as I know it works just fine. 
I have also run the tests against Mongoose 4.0.5 and they all pass.

Please try it and if you have any issues I may be able to look into it.

Thanks,
Tiago
