### ISSUE TITLE
plugin does not create version objects

### ISSUE THREAD

**Issue by glutz** [getlackey/mongoose-version#4]
Hi,

I'm using this plugin to create document versions of this (used the saintedlama/mongoose-version before):
module.exports = function(prefix, mongoose) {

```
var Schema = mongoose.Schema;
var versionedAnzeigeObject = require('lackey-mongoose-version');
var textSearch = require("mongoose-text-search");

var Anzeige = new Schema({

    id: {type: String, index: true},
    dataGroup: String,
    transport: {info: {}, baseRef: [ { type: Schema.ObjectId, ref: prefix + 'baseObject' } ] },
    LMIV: {},
    version: {},
    validUnit: String,
    isSearchable: Boolean,  
    development: {},
});

Anzeige.plugin(versionedAnzeigeObject, {
    mongoose: mongoose,
    collection: prefix + 'Anzeige_versions',
    logError: true
});

Anzeige.plugin(textSearch);


Anzeige.index({
        "transport.info.description.description": "text",
        "transport.info.description.descriptionShort": "text",
        ...
        "dataGroupName": "text",
    },
    {
        default_language: "german",
        weights: {
            "transport.info.description.description": 5,
            "transport.info.description.descriptionShort": 5,
             ...
            "dataGroupName": 4,
        },
        name: "textindexkws"
    });


return mongoose.model(prefix + 'Anzeige', Anzeige);
```

};

textindex works fine, I followed your example. but what I really wanted to have is that every time an document was updated a new version is saved in the versions collection, but nothing happened. collections are created and thats it. I am using nodejs 0.10.36, mongoose 2.10.1 and mongodb 3.02

Could you please have a look on this and tell me what I'm doing wrong?
thanks a lot 
Günter

**Comment by robmccardle** [comment]
Hi Günter, thanks for getting in touch; we're a bit short handed at the moment so can't get anyone to look at this right now I'm afraid. When @melono6 has a moment he might be able to point you in the right direction, cheers

**Comment by glutz** [comment]
Update:
plugin does not produce versions if you use findOneAndUpdate, only save creates a versioned document. but with save using the model described above:
- version counter in original collection counts, version array consists of only one document and is not an array of documents
- a version collection is ceated but  not needed because the version-collection was defined here
  Anzeige.plugin(versionedAnzeigeObject, {
  mongoose: mongoose,
  collection: prefix + 'Anzeige_versions',
  logError: true
  });

**Comment by robmccardle** [comment]
Thank you @glutz very useful testing. Would love a PR to fix if you (or anyone else) has capacity please. If not, your description will help us when we amend this in the future although I can't commit to a timeline at this point as all the guys are busy. Cheers

**Comment by relvao** [comment]
Hi @glutz 

The plugin works by hooking into mongoose [middleware](http://mongoosejs.com/docs/middleware.html), but not all methods trigger those events. findOneAndUpdate is one of those: 
https://github.com/Automattic/mongoose/issues/964

This isn't an issue with this plugin, but rather an issue with how mongoose treats those methods.

**Comment by glutz** [comment]
Hi @relvao 

that what I understand, but look into my last message. I have changed findOneAndUpdate to find and save but not array of previous documents appears. And why is a version collection created when a collection is defined with an different name?

**Comment by relvao** [comment]
@glutz 

I'm not sure I'm following your questions.
1. You're saying that the collection created to store the versions wasn't called "prefix + 'Anzeige_versions'"? If so, what was it called?
2. "but not array of previous documents appears". Are you saying that no version is created, or that you were expecting it to be in an array? As far as I remember we dropped the support for array versioning and we store each version as a document in the versions collection. Was this your question?

**Comment by glutz** [comment]
Hi @relvao 
thanks for this.
1. prefix ist a simple variable containg the project name, something like var prefix = 'P001'; The created collections are P001_Anzeige and P001_Anzeige_Versions
2. If you dropped array strategy then I can find my versioned documents referenced by refId?
Thanks for helping meto understand what I'm doing wrong and how to use this plugin

**Comment by relvao** [comment]
Yes you should use the refId. We dropped it because we had very large
documents and hit the max size limit... I assumed it would be safer to just
keep each version in it's own doc.

No problem. If you have any other questions feel free to reach out.

2015-10-22 21:49 GMT+01:00 glutz notifications@github.com:
