### ISSUE TITLE
Should not save a version when updating of the origin fails for some reason

### ISSUE THREAD

**Issue by daralthus** [getlackey/mongoose-version#6]
An example is a `VersionError` that happens when you try to update a document and the value of the provided [versionKey](http://mongoosejs.com/docs/guide.html#versionKey) is lower then the one currently in the db. 
It provides a dead simple solution to concurrency issues like outdated or out of order updates etc. so I will make a PR to make sure this is still supported, although it will have some performance penalties.
Imho other errors like validation errors should not be a problem, **if you ensure that this plugin is running last.** But that's something only the user can do.

**Comment by sielay** [comment]
Thanks for input. At the moment Lackey drift away from Mongo because its limitations. It may take bit longer time to validate PRs against legacy versions.
